version: "3.8"

services:
  db:
    image: postgres:14.5-alpine
    environment:
      # OSのタイムゾーン
      TZ: UTC
      # postgresのタイムゾーン
      PGTZ: UTC
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./api/tmp/db:/var/lib/postgresql/data"

  api:
    # ベースイメージとなるDockerfileを指定
    build:
      context: ./api
      # Dockerfile内のWORKDIRに値を渡す
      args:
        WORKDIR: "app"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      API_DOMAIN: "localhost:$FRONT_PORT"
    volumes:
      - "./api:/app"
    depends_on:
      - db
    # 公開したいポート番号：コンテナポート
    ports:
      - "$API_PORT:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: "app"
        API_URL: "http://localhost:$API_PORT"
    # コンテナで実行したいコマンド
    # Dockerfileではなくここで指定している理由は、yarn run devは開発用なので、本番でも使うDockerfileには書きたくないから。
    command: yarn run dev
    volumes:
      - "./front:/app"
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api